name: Socket

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  socket:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: socketdev/socket-action@v3
        with:
          npm-cache: false
